changelog:
  categories:
    - title: "🚀 Features"
      labels: ["feat"]

    - title: "🐞 Fixes"
      labels: ["fix"]

    - title: "📖 Documentation"
      labels: ["docs"]

    - title: "🧪 Tests"
      labels: ["test"]

    - title: "🔁 Continuous Integration"
      labels: ["ci"]

    - title: "🛠️ Refactors"
      labels: ["refactor"]

    - title: "🧹 Chores"
      labels: ["chore"]

    - title: "📦 Dependencies"
      labels: ["dependabot"]
