export declare type ParamSymbol =
  | "BNB.BSC"
  | "BTC.BTC"
  | "ETH.ETH"
  | "gETH"
  | "tBNB"
  | "tBTC"
  | "tMATIC"
  | "USDC.BSC"
  | "USDC.ETH"
  | "USDC"
  | "USDT.BSC"
  | "USDT.ETH";
export declare type ParamChainName =
  | "bsc_mainnet"
  | "bsc_testnet"
  | "btc_mainnet"
  | "btc_testnet"
  | "eth_mainnet"
  | "goerli_testnet"
  | "mumbai_testnet"
  | "zeta_mainnet"
  | "zeta_testnet";
export declare type ParamType =
  | "connector"
  | "erc20Custody"
  | "fungibleModule"
  | "pauser"
  | "systemContract"
  | "tss"
  | "tssUpdater"
  | "uniswapv2Factory"
  | "uniswapv2Router02"
  | "wZetaContract"
  | "zetaToken"
  | "zrc20";
