name: Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
    types:
      - synchronize
      - opened
      - reopened
      - ready_for_review

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: yarn install

      - name: Test with coverage
        run: yarn coverage || true
    
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
