name: Lint TS/JS/Sol (V2)

on:
  push:
    branches:
      - main
    paths:
      - 'v2/**'
  pull_request:
    branches:
      - "**"
    paths:
      - 'v2/**'
    types:
      - synchronize
      - opened
      - reopened
      - ready_for_review

defaults:
  run:
    working-directory: ./v2

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.1.0"
          registry-url: "https://registry.npmjs.org"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install Dependencies
        run: |
          yarn install
          forge soldeer update

      - name: Lint JavaScript/TypeScript
        run: yarn lint

      - name: Lint Solidity
        run: forge fmt --check
