name: Publish to NPM (V2)

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version to release, e.g., 10.0.0-rc2"
        required: true

defaults:
  run:
    working-directory: ./v2

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21"
          registry-url: "https://registry.npmjs.org"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      
      - name: Install Dependencies
        run: |
          yarn install
          forge soldeer update

      - name: Generate Files
        run: yarn generate

      - name: Determine NPM Tag
        id: determine-npm-tag
        run: |
          VERSION_TAG="${{ github.event.inputs.version }}"
          if [[ $VERSION_TAG == *"-"* ]]; then
            echo "NPM_TAG=${VERSION_TAG#*-}" >> $GITHUB_ENV
          else
            echo "NPM_TAG=latest" >> $GITHUB_ENV
          fi

      - name: Publish to NPM
        run: yarn publish --new-version ${{ github.event.inputs.version }} --tag ${{ env.NPM_TAG }} --no-git-tag-version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
